CREATE TABLE football_data(
division text,
match_date date, 
home_team text, 
away_team text, 
home_goals int, 
away_goals int, 
home_half_time_goals int,
away_half_time_goals int,
full_time_result text, 
referee text,
home_shots int, 
away_shots int, 
home_shots_on_target int,
away_shots_on_target int,
home_corners int,
away_corners int,
home_fouls int,
away_fouls int,
home_yellows int,
away_yellows int,
home_reds int,
away_reds int,
pinnacle_home float,
pinnacle_away float,
pinnacle_draw float,
PRIMARY KEY(match_date, home_team, away_team))