CREATE TABLE fantasy.game_weeks(
	round int,
	kickoff_time timestamp,
	player_name text,
	player_id int,
	value int,
	minutes int,
	total_points int,
	bonus_points int,
	bps int,
	goals_scored int,
	assists int,
	penalties_missed int,
	red_cards int,
	yellow_cards int,
	goals_conceded int,
	own_goals int,
	saves int,
	penalties_saved int,
	creativity float,
	influence float,
	threat float,
	ict_index float,
	transfers_in int,
	transfers_out int,
	transfers_balance int,
	selected int,
	fixture int,	
	team_h_score int,
	team_a_score int,
	was_home bool,
	opponent_team int,
	PRIMARY KEY(round, kickoff_time, player_name)
)
